version: '3'

services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.1.0
        environment:
            - discovery.type=single-node
        ports:
            - 9199:9200
        networks:
            teko:
    kibana:
        image: docker.elastic.co/kibana/kibana:7.1.0
        depends_on:
            - elasticsearch
        environment:
            - elasticsearch.hosts = http://elasticsearch:9200
        ports:
            - 5601:5601
        networks:
            teko:
networks:
    teko:
